### ISSUE TITLE
@2x images seem to be upscaled versions of their smaller sized thumbnails

### ISSUE THREAD

**Issue by Anoesj** [btobolaski/jekyll-retinamagick#4]
Hey!

First of all: I'm not good with Ruby, I guess I seriously just made a lucky guess with this.
I noticed that the 2x versions of images were really pixelated and ugly so I dived into your code and found out that changing this line:
```ruby
@commands[:resize] = "#{Integer(width) * 2}x#{Integer(height) * 2}"
```

...into this:
```ruby
@commands["resize"] = "#{Integer(width) * 2}x#{Integer(height) * 2}"
```

...fixes the problem and actually renders the 2x versions the way you would expect them to look.

Cheers,
Anoesj

**Comment by btobolaski** [comment]
Hmm... That is an interesting find. I wouldn't have expected that to make a difference.
